version: '3.9'

services:
  test:
    image: bretfisher/browncoat:v2.healthcheck
    stop_grace_period: 1m
    environment:
      DELAY_STARTUP: 0
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.http.services.test.loadbalancer.server.port=80"  
        - "traefik.http.routers.test-router.entrypoints=web,websecure"
        - "traefik.http.routers.test-router.tls=true"
        - "traefik.http.routers.test-router.rule=Host(`test.${DOMAIN_HOSTNAME}`)"
    networks:
      - external_network
      
  test_httping:
    image: bretfisher/httping
    entrypoint: ["httping", "-i", ".1", "-G", "-s", "-Y", "test/healthz"]  
    networks:
      - external_network

networks:
  external_network:
    name: ${EXTERNAL_NETWORK}
    external: true
